# Site settings
title: Hupermall
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:
email: "hupermall@hupersupport.com"
facebook_username: "hupermallcbba"
twitter_username:
github_username:
address:
  - line: "Av. Pando esq. Portales - Cochabamba, Bolivia"
 # - line:
 # Feel free to add more lines here 
telephone: "4548737"
copyright: "Hupermall Cochabamba"

# API settings
google_api_key:

# Build settings
markdown: kramdown